import figure from './figure'
import set from './set'
import terrain from './terrain'
import print from './print'
import character from './character'
import faction from './faction'
import releaseWave from './releaseWave'
import race from './race'
import accessory from './accessory'
export const schemaTypes = [figure, set, terrain, print, character, faction, releaseWave, race, accessory]